DJANGO_PORFOLIO/blog/urls.py
from django.urls import path
from .views import render_posts,post_detail
app_name='blog'
urlpatterns=[
    path('',render_posts,name='posts'),
    path('<int:post_id>',post_detail,name='post_detail')
]

DJANGO_PORFOLIO/django_porfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django_porfolio import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('blog/',include('blog.urls')),
    path('',include('tasks.urls')),
    path('referencia/',include('porfolio.urls'))
    

]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

DJANGO_PORFOLIO/porfolio/urls.py
from django.urls import path
from .views import referencia_create,referencia_delete,referencia_update,home

app_name = "porfolio"
urlpatterns = [
    path('home/',home,name='home'),
    path('referencia_create/',referencia_create,name="referencia_create"),
    path('referencia_update/<int:id>/',referencia_update,name='referencia_update'),
    path('referencia_delete/<int:id>/',referencia_delete,name='referencia_delete'),
    ]

DJANGO_PORFOLIO/tasks/urls.py
from django.urls import path
from.views import signup, signin,base,signout

app_name = "tasks"
urlpatterns = [
    path("signup/",signup, name="signup"),
    path("",base,name='base'),
    path("signin/",signin,name='signin'),
    path("signout/",signout,name='signout')
]

DJANGO_PORFOLIO/blog/models.py
from django.db import models
import datetime
class Post(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    image=models.ImageField(upload_to='blog/images')
    date = models.DateField(default=datetime.date.today)

DJANGO_PORFOLIO/porfolio/models.py
from django.db import models
from django.db.models.fields import DecimalField, CharField, URLField,TextField,DateField
from django.db.models.fields.files import ImageField
import datetime

class Project(models.Model):
    title = CharField(max_length=100)
    descripcion = CharField(max_length=250)
    image = ImageField(upload_to="porfolio/images/")
    url = URLField(blank=True)

class Experience(models.Model):
    institucion_del_curso=CharField(max_length=100)
    descripcion_curso=TextField()
    fecha_curso = DateField(default=datetime.date.today)
    numero_horas=DecimalField(max_digits=5, decimal_places=2)


class Relacion(models.Model):
    descripcion = CharField(max_length=50, unique=True)

    def __str__(self):
        return self.descripcion

class Referencias_laborales(models.Model):
    nombre_test=CharField(max_length=30)
    relacion = models.ma(Relacion,on_delete=models.CASCADE)
    telefono=CharField(max_length=10)
    correo=CharField(max_length=80)
    descripcion=models.TextField()
    def __str__(self):
        return f"{self.nombre_test} - {self.relacion.descripcion}"

DJANGO_PORFOLIO/tasks/models.py
from django.db import models

# Create your models here.

DJANGO_PORFOLIO/porfolio/forms.py
from django import forms
from .models import Referencias_laborales

class Referencias(forms.ModelForm):
    class Meta:
        model=Referencias_laborales
        fields=['nombre_test','relacion','telefono','correo','descripcion']

DJANGO_PORFOLIO/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post
from django.contrib.auth.decorators import login_required

@login_required
def render_posts(request):
    posts=Post.objects.all()
    return render(request, "posts.html", {"posts": posts})


@login_required
def post_detail(request,post_id):
    post=get_object_or_404(Post,pk=post_id)
    return render(request,"post_detail.html",{"post":post})

DJANGO_PORFOLIO/porfolio/views.py
from django.shortcuts import redirect, render
from .models import Project,Experience,Referencias_laborales
from django.contrib.auth.decorators import login_required
from .forms import Referencias

@login_required
def home(request):
    projects=Project.objects.all()
    experiences=Experience.objects.all()
    testimonios=Referencias_laborales.objects.all()
    return render(request, "home.html", {"projects": projects ,"experience":experiences,"testimonio":testimonios})


def referencia_create(request):
    data = {"title": "Referencias laborales", "title1": "Añadir referencias"}
    if request.method == "POST":
        form = Referencias(request.POST)
        if form.is_valid():
            form.save()
            return redirect("porfolio:home")
        else:
            data["form"] = form
            data["error"] = "Error al crear referencia."
            return render(request, "referencias/form.html", data)
    else:
        form = Referencias()
        data["form"] = form
    print(form)
    return render(request, "referencias/form.html", data)


def referencia_delete(request, id):
    referencia= Referencias_laborales.objects.get(id=id)
    data = {"title": "Eliminar", "title1": "Eliminar Referencias", "referencia": referencia}
    if request.method == "POST":
        referencia.delete()
        return redirect("porfolio:home")
    return render(request, "referencias/delete.html", data)


def referencia_update(request, id):
    data = {"title": "Referencias", "title1": "Editar Referencia"}
    referencia= Referencias_laborales.objects.get(pk=id)  # doctor1
    if request.method == "POST":
        form = Referencias(request.POST, instance=referencia)
        if form.is_valid():
            form.save()
            return redirect("porfolio:home")
        else:
            data["form"] = form
            data["error"] = "Error al editar referencia."
            return render(request, "referencias/form.html", data)
    else:
        form = Referencias(instance=referencia)
        data["form"] = form
    print(form)
    return render(request, "referencias/form.html", data)

DJANGO_PORFOLIO/tasks/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
def signup(request):
    if request.method=='GET':
        return render(request, "signup.html", {"form": UserCreationForm})
    else:
        if request.POST['password1']==request.POST['password2']:
            # register user
            try:
                user=User.objects.create_user(
                username=request.POST["username"], password=request.POST["password1"]
                )
                user.save()
                login(request, user)
                return redirect('porfolio:home')
            except IntegrityError:
                return render(request, "signup.html", {"form": UserCreationForm, 'error':'User ya existe'})
        else:
            return render(
                request,
                "signup.html",
                {"form": UserCreationForm, "error": "Password do not match"},
            )
def base(request):
    return render( request,"base.html")

def signin(request):
    print('enviando formulario')
    if request.method=='GET':
        return render(request, "signin.html", {"form": AuthenticationForm})
    else:
        user=authenticate(request, username=request.POST['username'],password=request.POST['password'])
        if user is None:
            return render(request, "signin.html", {"form": AuthenticationForm,'error':'Usuario o Contraseña es incorrecto'})
        else:
            login(request,user)
            return redirect('porfolio:home')


def signout(request):    
    logout(request)
    return redirect('tasks:base')

DJANGO_PORFOLIO/blog/templates/post_detail.html
{% extends 'layout.html' %}
{%block content%}
    <div class="text-center">
        <h2>{{post.title}}</h2>
        <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>
        <img src="{{post.image.url}}" alt="post.title" class=" img-fluid">

        <div class="my-4">
            <p class="text-justify">{{post.description|safe}}</p>
        </div>
    </div>
    
    
{%endblock%}

DJANGO_PORFOLIO/blog/templates/posts.html
{% extends 'layout.html' %}
{%block content%}
<h1>post</h1>
{% for post in posts%}
<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="post.title" class="img-fluid">
            </div>
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <p>{{post.description|striptags|truncatechars:100}}</p>
                <p>{{post.date|date:'M d Y'}}</p>
        
                <a href="{%url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{%endblock%}

DJANGO_PORFOLIO/porfolio/templates/home.html
{% extends 'layout.html' %}
{% load custom_filters %}
{%block content%}
{% load static %}

<header class="row bg-dark">
    <div class="col-md-4 ">
        <img src="{% static 'porfolio/perfil.jpg'%}" alt="">
    </div>

    <div class="col-md-8 my-auto">
        <h1>I am <strong>Ryan Ray</strong></h1>
        <h3>I am a Python FullStack Developer</h3>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum, nobis eveniet magnam voluptatibus rem earum hic ut odit, ad omnis debitis facere mollitia blanditiis quisquam perferendis consectetur ea at accusamus ipsam explicabo! Distinctio impedit rerum delectus velit minus hic itaque eaque quod quasi repellat perspiciatis recusandae esse dolores nesciunt similique, provident blanditiis veniam ex consequatur alias nulla ad assumenda pariatur veritatis! Iusto magni incidunt repellendus consectetur autem quidem! At alias nemo vero accusantium provident repudiandae aliquid eos itaque aliquam quasi error beatae, praesentium in sit, ut voluptatum ipsum corporis ad incidunt obcaecati, rem facere? Laudantium repellat eveniet culpa vel maiores fugit a voluptates molestiae sequi vero nulla blanditiis provident reiciendis voluptatibus delectus distinctio, pariatur porro sint tempora natus aperiam officia recusandae, eligendi est? Corporis dignissimos, quibusdam doloribus sunt error quas ullam ab vel vitae, atque laudantium. Totam asperiores corrupti assumenda unde ex autem voluptatum aut atque fugit, magni facere nam cupiditate at labore, consequuntur aspernatur numquam eaque exercitationem non! Quos voluptate expedita similique nulla natus inventore blanditiis sed quo dignissimos incidunt ipsa suscipit quidem, facere dolor, quibusdam ipsam minus velit? Commodi eveniet qui, laboriosam dolore non nihil facilis vero aliquid explicabo deserunt fugiat quibusdam a ea soluta, voluptatem excepturi minima!</p>
        <a href="{% static 'porfolio/cv.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3">Download cv</a>
    </div>
</header>


<div class="row my-4 text-center">
    <h3>My Projects</h3>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cumque.</p>
    {% for project in projects %}
    <div class="col-md-4 p-4 ">
        <div class="card bg-black card-project text-light">
            <img src="{{project.image.url}}" alt="{{project.title}}" class="card img-top" />
            <div class="card-body">
            <h2>{{project.title}}</h2>
            <p>{{project.descripcion}}</p>
            {% if project.url %}
                <a href="{{project.url}}" class="btn btn-light round-0 btn-sm" target="_blank">Link del proyecto</a>
            {% endif %}
            </div>
        </div>

    </div>
    {% endfor %}

</div>

<div class="row my-4 text-center">
    <h3>My Experience</h3>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cumque.</p>
    {% for experiencia in experience %}
    <div class="col-md-4 p-4 ">
        <div class="card bg-black card-project text-light">
            <img src="{{project.image.url}}" alt="{{project.title}}" class="card img-top" />
            <div class="card-body">
            
            <h2>{{experiencia.institucion_del_curso}}</h2>
            <p>{{experiencia.descripcion_curso}}</p>
            <p><strong>Feahca de realizacion:</strong>{{experiencia.fecha_curso}}</p>
            <p><strong>Horas:</strong> {{experiencia.numero_horas|horas_y_minutos}}</p>
            </div>
        </div>

    </div>
    {% endfor %}

</div>
<div class="row my-4 text-center">
    <h3>Mis referencias laborales</h3>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cumque.</p>
    <a class="btn btn-primary mb-sm-2" href="{% url 'porfolio:referencia_create' %}">Nuevo registro</a>
    {% for referencia in testimonio %}

    <div class="col-md-4 p-4 ">
        <div class="card bg-black card-project text-light">
            <div class="card-body">
            
            <h2>{{referencia.nombre_test}}</h2>
            <p>{{referencia.relacion}}</p>
            <p><strong>Telefono:</strong>{{referencia.telefono}}</p>
            <p><strong>Correo:</strong> {{referencia.correo}}</p>
            <p>{{referencia.descripcion}}</p>
            </div>
            <td>
                <a href="{% url 'porfolio:referencia_update' referencia.id %} "class="btn btn-warning btn-sm">Editar</a>
                <a href="{% url 'porfolio:referencia_delete' referencia.id %} "class="btn btn-danger btn-sm">Eliminar</a>
            </td>
        </div>

    </div>
    {% endfor %}

</div>
{%endblock%}

DJANGO_PORFOLIO/porfolio/templates/layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django porfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    {% include 'partials/navbar.html' %}
    <div class="container p-4">
    {%block content%}
    {%endblock%}
    </div>
</body>
    
    
</html>

DJANGO_PORFOLIO/porfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    {% if user.is_authenticated %}
      <a class="navbar-brand" fw-blod fst-italic href="{% url 'porfolio:home' %}">RR</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    {% else %}
      <a class="navbar-brand" fw-blod fst-italic href="/">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    {% endif %}
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% static 'porfolio/cv.pdf' %}" target="_blank">Download</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% url 'tasks:signout' %}">Cerrar sesión</a>
          </li> 
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:signin' %}">Iniciar sesión</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% url 'tasks:signup' %}">Registrarse</a>
          </li>
          
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

DJANGO_PORFOLIO/porfolio/templates/referencias/delete.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{title}}</title>
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <style>
        body {
            background-color: #f7f9fc; /* Suave fondo gris claro */
            font-family: 'Arial', sans-serif;
        }

        h1 {
            color: #007bff; /* Azul para resaltar el título */
        }

        .form-container {
            background-color: white; 
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            max-width: 600px;
            margin: 0 auto;
        }

        .btn-outline-success {
            background-color: #28a745;
            color: white;
            border-color: #28a745;
        }

        .btn-outline-success:hover {
            background-color: #218838;
            border-color: #1e7e34;
        }

        .btn-outline-warning {
            color: #ffc107;
            border-color: #ffc107;
        }

        .btn-outline-warning:hover {
            background-color: #e0a800;
            color: white;
            border-color: #d39e00;
        }

        .form-container a {
            text-decoration: none;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="form-container">
        <form class="form-container" method="POST">
            {% csrf_token %}
            <h1 class="title">{{ title1 }}</h1>
            <h2>¿Desea Eliminar la refereancia?
                <span>{{ referencia.id }} - {{referencia.nombre_test }} {{ referencia.relacion }}</span>
            </h2>
            <div>
                <button class="btn blue" type="submit">Eliminar</button>
                <a class="btn red" href="{% url 'porfolio:home' %}" >Regresar</a>
            </div>
        </form>
    </div>
</div> 

    <!-- Bootstrap JS and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

DJANGO_PORFOLIO/porfolio/templates/referencias/form.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="form-container">
            <h1 class="text-center mb-4">{{ title1 }}</h1>
            {% load crispy_forms_tags %}  
            <form method="POST" class="m-4"> 
                {% csrf_token %}
                {{ form|crispy}}
                <div class="d-flex justify-content-end mt-4">
                    <button class="btn btn-outline-success me-2" type="submit">Grabar referencia</button>
                    <a class="btn btn-outline-warning" href="{% url 'porfolio:home' %}">Cancelar</a>
                </div>
            </form>
        </div>
    </div>    
{% endblock %}

DJANGO_PORFOLIO/tasks/templates/base.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<style>
    body {
        background-color: #343a40; /* Color de fondo oscuro */
    }
</style>

<div class="container mt-5 text-center">
    <h1 class="text-center text-white">Bienvenido a nuestro porfolio</h1>
    <p class="lead text-light">Aquí puedes explorar y disfrutar de nuestro contenido exclusivo.</p>
    
    <div class="mt-4">
        <a href="{% url 'tasks:signup' %}" class="btn btn-primary me-2">Registrarse</a>
        <a href="{% url 'tasks:signin' %}" class="btn btn-secondary">Iniciar Sesión</a>
    </div>
</div>

{% endblock %}

DJANGO_PORFOLIO/tasks/templates/signin.html
{% extends 'layout.html' %}
{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<style>
    body {
        background-color: #343a40; /* Color de fondo oscuro */
    }
</style>

<main class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5">
            <form method="POST" class="bg-dark text-white p-4 rounded shadow">
                <h1 class="text-center">Iniciar Sesión</h1>
                {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endif %}
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Nombre de usuario:</label>
                    <input type="text" name="username" id="username" class="form-control bg-secondary text-white" placeholder="Escribe tu nombre de usuario" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Contraseña:</label>
                    <input type="password" name="password" id="password" class="form-control bg-secondary text-white" placeholder="Escribe tu contraseña" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">
                    Iniciar Sesión
                </button>
            </form>
        </div>
    </div>
</main>

{% endblock %}


DJANGO_PORFOLIO/tasks/templates/signup.html
{% extends 'layout.html' %}
{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<style>
    body {
        background-color: #343a40; /* Color de fondo oscuro */
    }
</style>

<main class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5">
            <form method="POST" class="bg-dark text-white p-4 rounded shadow">
                <h1 class="text-center">Registro</h1>
                {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endif %}
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Nombre de usuario:</label>
                    <input type="text" name="username" id="username" class="form-control bg-secondary text-white" placeholder="Escribe tu nombre de usuario" required>
                </div>
                <div class="mb-3">
                    <label for="password1" class="form-label">Contraseña:</label>
                    <input type="password" name="password1" id="password1" class="form-control bg-secondary text-white" placeholder="Escribe tu contraseña" required>
                </div>
                <div class="mb-3">
                    <label for="password2" class="form-label">Confirmar contraseña:</label>
                    <input type="password" name="password2" id="password2" class="form-control bg-secondary text-white" placeholder="Confirma tu contraseña" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">
                    Registrarse
                </button>
            </form>
        </div>
    </div>
</main>

{% endblock %}